### ISSUE TITLE
hostapd.service failed to load

### ISSUE THREAD

**Issue by celi28** [jenssegers/RTL8188-hostapd#12]
Hi guy,
I follow your blog [link](http://www.jenssegers.be/43/Realtek-RTL8188-based-access-point-on-Raspberry-Pi).
When I tried to install it on my raspeberry, after `sudo service hostapd restart`, I have this issue:

```
Failed to restart hostapd.service: Unit hostapd.service failed to load: No such file or directory.
```

Can you help me to solve it?

Thanks

**Comment by sebschmitt** [comment]
@gregduc try using `make` and `make install` for wpa_supplicant first
This worked for me

**Comment by harshadyeola** [comment]
@sebschmitt 
This does not work

**Comment by ivanwolodin** [comment]
Absolutely does not work

**Comment by viasisco** [comment]
maybe try sudo /etc/init.d/hostapd restart instead. The makefile install it in the ini.d directory.

**Comment by MatthewWolff** [comment]
@viasisco I tried your fix:
sudo /etc/init.d/hostapd restart
[....] Restarting hostapd (via systemctl): hostapd.serviceFailed to restart hostapd.service: Unit hostapd.service failed to load: No such file or directory.
 failed!

**Comment by nisarg09** [comment]
sudo /etc/init.d/hostapd restart worked for me.
