### ISSUE TITLE
accept_mac_file does not seem to be respected

### ISSUE THREAD

**Issue by urda** [jenssegers/RTL8188-hostapd#5]
Given:

``` bash
macaddr_acl=1
accept_mac_file=/etc/hostapd/mac_accept
```

This version of `hostapd` and driver does not seem to be accessing or respecting the `accept_mac_file` restrictions

**Comment by jenssegers** [comment]
Can you check the last beta tag?

**Comment by urda** [comment]
Considering this was filled over two months ago, I don't have access to that hardware at this time :cry: . If I can regain access to it, I'll try again.
